---
title: "Conociendo a Dalia"
---

## ¿Quién soy?

Me llamo Dalia Castro Bueno, nací en Barranquilla pero vivo en Soledad. A continuación enumeraré algunas cositas sobre mí: 

1. Me encanta la pizza y el queso, 
2. Me gusta salir a pasear con mi familia,
3. Adoro pasar el tiempo con mi novia,
4. Estoy transicionando a una dieta vegetariana,
5. Mis pasatiempos son: dibujar, cocinar, leer y ver series,
6. Me gusta visibilizar problemáticas sociales a través de mis redes,
7. Me gustaría crear más contenido en mis redes sociales,
8. Me llama la atención el marketing digitál (de hecho, estoy haciendo un curso al respecto)


## ¿Qué he logrado?
Soy ingeniera industrial de la Universidad del Norte, a mitad de carrera decidí estudiar matemáticas puras, y ya voy por mi último semestre. Además, a través de un proyecto empecé la maestria en ingeniería industrial. 

En cuanto a experiencia laboral, trabajo desde hace más de un año en la Universidad del Norte, primero cómo asistente administrativo de la dirección de sostenibilidad y ahora cómo analista de datos lider para proyectos de consultoría. 

Además fui monitora de materias cómo  “Logística y
distribución” y “Planeación, programación y control de la
producción” por más de un año. Y estudié italiano becada con el semillero de idiomas.


## ¿Qué quiero hacer?

Quiero primero terminar mi pregrado en matemáticas, y continuar con mis estudios de maestria. Luego me gustaría iniciar el doctorado becada o financiada por un proyecto. 

También quiero mejorar mi inglés y practicar el italiano (para que no se me olvide). 

## ¿Dónde me puedes conocer mejor?

En mis redes sociales: 

- [LinkedIn](https://www.linkedin.com/in/dalia-castro-bueno)
- [Instagram](https://www.instagram.com/daliaacb02?igsh=OWN6NXV4dXhpdXZ5)
